# Generated by Django 4.2.8 on 2024-01-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.JSONField(blank=True, default=dict, verbose_name='service')),
                ('start_time', models.TimeField(blank=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('date', models.DateField(blank=True, verbose_name='date')),
                ('is_open', models.BooleanField(blank=True, verbose_name='open status')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('images', models.ImageField(blank=True, upload_to='services/')),
                ('cancellation_policy', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry', models.TextField(blank=True, verbose_name='inquiry')),
                ('reply', models.TextField(blank=True, default='', verbose_name='reply')),
                ('desired_time', models.TimeField(blank=True, null=True, verbose_name='desired time')),
                ('desired_date', models.DateField(blank=True, verbose_name='desired date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=8)),
            ],
            options={
                'verbose_name': 'service request',
                'verbose_name_plural': 'service requests',
            },
        ),
    ]
