# Generated by Django 4.2.8 on 2024-01-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='users.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.service', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='service',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='services', to='providers.provider', verbose_name='providers'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='providers.schedule', verbose_name='schedule'),
        ),
    ]
