# Generated by Django 4.2.8 on 2023-12-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_open',
            field=models.BooleanField(blank=True, default=True, verbose_name='open status'),
            preserve_default=False,
        ),
    ]
