# Generated by Django 4.2.8 on 2024-01-01 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='alias')),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='provider', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='identity')),
                ('qualifications', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('ratings', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('opening_time', models.TimeField(blank=True, verbose_name='opening time')),
                ('closing_time', models.TimeField(blank=True, verbose_name='closing time')),
                ('provider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='providers.provider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
    ]
