# Generated by Django 4.2.8 on 2023-12-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week'),
        ),
    ]
